apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookstore-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookstore-backend
  template:
    metadata:
      labels:
        app: bookstore-backend
    spec:
      containers:
        - name: backend
          image: akhlab/bookstore-backend
          ports:
            - containerPort: 5002
---
apiVersion: v1
kind: Service
metadata:
  name: bookstore-backend-service
spec:
  selector:
    app: bookstore-backend
  ports:
    - protocol: TCP
      port: 5002
      targetPort: 5002
  type: NodePort
